# Generated by Django 5.1.7 on 2025-03-22 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street",
                    models.CharField(max_length=100, verbose_name="Street Address"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                (
                    "state",
                    models.CharField(max_length=50, verbose_name="State/Province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postal Code"),
                ),
                ("country", models.CharField(max_length=50, verbose_name="Country")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Address"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(max_length=20, verbose_name="Primary Phone"),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Secondary Phone"
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="Email Verified"),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(default=False, verbose_name="Phone Verified"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FullName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "addresses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customers",
                        to="customer.address",
                        verbose_name="Addresses",
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.contact",
                        verbose_name="Contact Information",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
                (
                    "full_name",
                    models.OneToOneField(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.fullname",
                        verbose_name="Full Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loyalty_points",
                    models.IntegerField(default=0, verbose_name="Loyalty Points"),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=10,
                        verbose_name="Tier",
                    ),
                ),
                (
                    "join_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Join Date"),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_profile",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Customer",
                "verbose_name_plural": "Loyalty Customers",
            },
        ),
        migrations.CreateModel(
            name="NewCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_offer_used",
                    models.BooleanField(
                        default=False, verbose_name="Welcome Offer Used"
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_profile",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Customer",
                "verbose_name_plural": "New Customers",
            },
        ),
    ]
